### ISSUE TITLE
STON.fi swap_jetton_to_ton

### ISSUE THREAD

**Issue by Sometimes-Coder** [nessshon/tonutils#17]
https://github.com/nessshon/tonutils/blob/30846cbb0adb667e2211f7114ae726011204428c/tonutils/wallet/contract/_base.py#L961

Why would you use `forward_amount + fee_amount` if only fee_amount is sufficient?
- 
![image](https://github.com/user-attachments/assets/660e6704-1573-4bb9-b664-eecd93e76419)

**Comment by nessshon** [comment]
@Sometimes-Coder The reason for using forward_amount + fee_amount instead of just fee_amount could be tied to the specific implementation logic or formula being applied. According to the [STON.fi documentation](https://docs.ston.fi/docs/developer-section/sdk/dex-v1/swap#formulas), the swap logic may require the total amount, including both the forward amount and the fee, to calculate correctly under certain conditions.

For reference, I was looking at an example implementation [here](https://github.com/lapismyt/ston-fi.py). If you believe this approach is incorrect and have strong evidence it could lead to issues, feel free to propose changes via a PR (Pull Request). However, ensure it won't unintentionally affect functionality or introduce errors before proceeding.

**Comment by Sometimes-Coder** [comment]
> @Sometimes-Coder The reason for using forward_amount + fee_amount instead of just fee_amount could be tied to the specific implementation logic or formula being applied. According to the [STON.fi documentation](https://docs.ston.fi/docs/developer-section/sdk/dex-v1/swap#formulas), the swap logic may require the total amount, including both the forward amount and the fee, to calculate correctly under certain conditions.
> 
> For reference, I was looking at an example implementation [here](https://github.com/lapismyt/ston-fi.py). If you believe this approach is incorrect and have strong evidence it could lead to issues, feel free to propose changes via a PR (Pull Request). However, ensure it won't unintentionally affect functionality or introduce errors before proceeding.

I guess for TON to Jetton this is correct, but for Jetton to TON it should just be 0.17 as the documentation says, or 0.19 just in case.
- 
![image](https://github.com/user-attachments/assets/c6ced4b2-dba4-4be9-9f08-81bd2057ae0d)
